### ISSUE TITLE
 can you invite me to the Discord channel please?

### ISSUE THREAD

**Issue by MrGongqi** [posit-conf-2023/dataviz-ggplot2#1]
Hello, I am sorry that I found out about this too late and missed the opportunity. I have a great need for using ggplot2 for scientific visualization and would like to further improve my skills. I hope to exchange ideas and help each other with everyone. Can you please invite me to the Discord channel?

**Comment by z3tt** [comment]
I am sorr, the Discord channel was a closed channel for workshop participants and the server is offline again. If you're seeking feedback from other ggplot2 user, consider to [join the R4DS community on Slack](https://rfordatasci.com/) which also offers a dedicated dataviz channel to address ggplot2 questions. Hope this helps!
